In [2]:
from ledger_loader import get_final_ledger
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta

In [3]:
ledger = get_final_ledger()
ledger

c:\Users\Administrator\Videos\ledger_loader.py:44: DtypeWarning: Columns (3: MemberID) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

         ClientID           CreatedAt LedgerType    Debit  Credit   Balance
0          P71057 2026-08-27 23:59:58       BILL   123.00    0.00  10244.65
1         M155101 2026-08-27 23:59:55   WITHDRAW  5000.00    0.00   4693.52
2          P62149 2026-08-27 23:59:52       BILL     0.00  353.41  12655.67
3         M129746 2026-08-27 23:59:47       BILL   158.00    0.00  11380.35
4         M129746 2026-08-27 23:59:47       BILL    62.00    0.00  11537.85
...           ...                 ...        ...      ...     ...       ...
11071980   V22798 2026-10-21 00:00:44       BILL     0.00  430.00  45777.57
11071981  R107793 2026-10-21 00:00:23       BILL     1.72    0.00    484.24
11071982   G25038 2026-10-21 00:00:13       BILL   390.45    0.00   7716.31
11071983   G25038 2026-10-21 00:00:13       BILL    42.50    0.00   8106.76
11071984  S104093 2026-10-21 00:00:00       BILL     0.00    0.00   4239.78

[11071985 rows x 6 columns]

In [ ]:
entry = ['BILL']
led = ledger[ledger['LedgerType'].isin(entry)].copy()
led

         ClientID           CreatedAt LedgerType   Debit  Credit   Balance
0          P71057 2026-08-27 23:59:58       BILL  123.00    0.00  10244.65
2          P62149 2026-08-27 23:59:52       BILL    0.00  353.41  12655.67
3         M129746 2026-08-27 23:59:47       BILL  158.00    0.00  11380.35
4         M129746 2026-08-27 23:59:47       BILL   62.00    0.00  11537.85
5          S39238 2026-08-27 23:59:47       BILL   91.00    0.00   9889.66
...           ...                 ...        ...     ...     ...       ...
11071980   V22798 2026-10-21 00:00:44       BILL    0.00  430.00  45777.57
11071981  R107793 2026-10-21 00:00:23       BILL    1.72    0.00    484.24
11071982   G25038 2026-10-21 00:00:13       BILL  390.45    0.00   7716.31
11071983   G25038 2026-10-21 00:00:13       BILL   42.50    0.00   8106.76
11071984  S104093 2026-10-21 00:00:00       BILL    0.00    0.00   4239.78

[9766126 rows x 6 columns]

In [9]:
led['Month'] = led['CreatedAt'].dt.to_period('M')
led

,ClientID,CreatedAt,LedgerType,Debit,Credit,Balance,Month
0,P71057,2026-08-27 23:59:58,BILL,123.00,0.00,10244.65,2026-08
2,P62149,2026-08-27 23:59:52,BILL,0.00,353.41,12655.67,2026-08
3,M129746,2026-08-27 23:59:47,BILL,158.00,0.00,11380.35,2026-08
4,M129746,2026-08-27 23:59:47,BILL,62.00,0.00,11537.85,2026-08
5,S39238,2026-08-27 23:59:47,BILL,91.00,0.00,9889.66,2026-08
...,...,...,...,...,...,...,...
11071980,V22798,2026-10-21 00:00:44,BILL,0.00,430.00,45777.57,2026-10
11071981,R107793,2026-10-21 00:00:23,BILL,1.72,0.00,484.24,2026-10
11071982,G25038,2026-10-21 00:00:13,BILL,390.45,0.00,7716.31,2026-10
11071983,G25038,2026-10-21 00:00:13,BILL,42.50,0.00,8106.76,2026-10
11071984,S104093,2026-10-21 00:00:00,BILL,0.00,0.00,4239.78,2026-10

In [10]:
activity = led[['ClientID', 'Month']].drop_duplicates()
activity

         ClientID    Month
0          P71057  2026-08
2          P62149  2026-08
3         M129746  2026-08
5          S39238  2026-08
6          R32184  2026-08
...           ...      ...
11068524   G77341  2026-10
11068734  C132255  2026-10
11069159   S61133  2026-10
11069190   T39938  2026-10
11071576  V215151  2026-10

[106969 rows x 2 columns]

In [12]:
activity['Cohort'] = activity.groupby('ClientID')['Month'].transform('min')
activity

         ClientID    Month   Cohort
0          P71057  2026-08  2026-01
2          P62149  2026-08  2026-02
3         M129746  2026-08  2026-06
5          S39238  2026-08  2025-11
6          R32184  2026-08  2025-11
...           ...      ...      ...
11068524   G77341  2026-10  2026-02
11068734  C132255  2026-10  2026-06
11069159   S61133  2026-10  2026-01
11069190   T39938  2026-10  2025-11
11071576  V215151  2026-10  2026-10

[106969 rows x 3 columns]